import Cursor from "@/components/CustomCursor/Cursor";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin='anonymous' />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&amp;family=Jost:wght@400;500;600;700&amp;display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="css/vendors.css" />
        <link rel="stylesheet" href="css/main.css" />
      </head>
      <body>
        <main>
          <Cursor/>
          <Header />
          {children}
          <Footer />

          <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAz77U5XQuEME6TpftaMdX0bBelQxXRlM"></script>
          <script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js"></script>
          <Script strategy="afterInteractive" src="js/vendors.js" ></Script>
          <Script strategy="afterInteractive" src="js/main.js" ></Script>
        </main>
      </body>
    </html>
  );
}
